name: Frontend Deploy

on:
  push:
    branches:
      - stage
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Copy the right env file for the branch
      - name: Setup environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            cp .env.prod .env
          else
            cp .env.stage .env
          fi

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build app
        run: CI=false npm run build

      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:v14.16.0
        with:
          args: deploy --only hosting:${{ github.ref == 'refs/heads/main' && 'prod' || 'stage' }} --project ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROJECT_PROD || secrets.FIREBASE_PROJECT_STAGE }}
        env:
          GCP_SA_KEY: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_SERVICE_ACCOUNT_PROD || secrets.FIREBASE_SERVICE_ACCOUNT_STAGE }}
          FIREBASE_PROJECT: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROJECT_PROD || secrets.FIREBASE_PROJECT_STAGE }}